version: "3"

services:
  site:
    build: ./.
    image: muncs/picocad-site
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:8080:80
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.services.picocad.loadbalancer.server.port=80"
      - "traefik.http.routers.picocad.rule=Host(`picocad.muncompsci.ca`)"
      - "traefik.http.routers.picocad.entrypoints=websecure"
      - "traefik.http.routers.picocad.tls.certresolver=myresolver"

networks:
  web:
    external: true
